"""Initial migration.

Revision ID: 2b14aa0769c9
Revises: 
Create Date: 2025-07-29 10:43:51.326722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b14aa0769c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('prize_places', sa.Integer(), nullable=True),
    sa.Column('manual_results', sa.Boolean(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_start_date'), ['start_date'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('balance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_amount', sa.Float(), nullable=False),
    sa.Column('new_balance', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_history_timestamp'), ['timestamp'], unique=False)

    op.create_table('participants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tournament_id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=True),
    sa.Column('away_team', sa.String(length=100), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('home_score_prediction', sa.Integer(), nullable=True),
    sa.Column('away_score_prediction', sa.Integer(), nullable=True),
    sa.Column('home_score_actual', sa.Integer(), nullable=True),
    sa.Column('away_score_actual', sa.Integer(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tournament_id', 'match_id', name='_user_tournament_match_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('participants')
    with op.batch_alter_table('balance_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_history_timestamp'))

    op.drop_table('balance_history')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_start_date'))

    op.drop_table('tournament')
    # ### end Alembic commands ###
