"""Add sport to Tournament

Revision ID: 3eedb08bdef9
Revises: 4a5425e34197
Create Date: 2025-08-08 12:49:09.585677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eedb08bdef9'
down_revision = '4a5425e34197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport', sa.String(length=50), nullable=False, server_default='football'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('sport')

    # ### end Alembic commands ###
