"""Re-add join_date to User with server_default

Revision ID: 4a5425e34197
Revises: a75e2e5fd92a
Create Date: 2025-07-30 14:53:36.170344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5425e34197'
down_revision = 'a75e2e5fd92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('join_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('join_date')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
