"""add balance history table

Revision ID: 64c6067a28b1
Revises: bb97e931b69b
Create Date: 2025-07-23 13:49:19.136781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c6067a28b1'
down_revision = 'bb97e931b69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_history_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_history_timestamp'))

    op.drop_table('balance_history')
    # ### end Alembic commands ###
