"""add end_date to tournament

Revision ID: 74a5011c5969
Revises: a1276ba7e92f
Create Date: 2025-07-30 07:50:27.301814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a5011c5969'
down_revision = 'a1276ba7e92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tournament_end_date'), ['end_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_end_date'))
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
