"""add leagues field to tournament

Revision ID: 7b2fd310f3ca
Revises: 9b53fbb50822
Create Date: 2025-07-24 09:53:37.609539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2fd310f3ca'
down_revision = '9b53fbb50822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leagues', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('leagues')

    # ### end Alembic commands ###
