"""add matches field to tournament

Revision ID: 9e833352ba49
Revises: 7b2fd310f3ca
Create Date: 2025-07-24 10:01:00.709162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e833352ba49'
down_revision = '7b2fd310f3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matches', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('matches')

    # ### end Alembic commands ###
