"""add matches_json to tournament

Revision ID: a1276ba7e92f
Revises: 2b14aa0769c9
Create Date: 2025-07-29 11:27:12.958327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1276ba7e92f'
down_revision = '2b14aa0769c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matches_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('matches_json')

    # ### end Alembic commands ###
